### ISSUE TITLE
webhooks not working on rails 4.1.7

### ISSUE THREAD

**Issue by francescob** [smartinez87/exception_notification#246]
when i try to send exception notifications using a webhook in rails 4.1.7 it fails with this error:

```
WARN -- : An error occurred when sending a notification using 'webhook' notifier. NoMethodError: undefined method `http_method' for #<ActionDispatch::Request:0x007f8858b6cdc0>
```

this is the code i used:

```
  :webhook => {
    :url => 'https://bitbucket.org/api/1.0/repositories/username/repo_name/issues',
    :basic_auth => {
      :username => 'xxxx',
      :password => 'xxxx'
      },
    :options => {
      :body => {
        :title => "adasdas",
        :content => "SDasdassad"
      }
    }
  }
```
